function params = defaults_dual(params)
%DEFAULTS_DUAL Set default options for the dual/harmonic-map formulation.
    if nargin < 1
        params = struct();
    end

    defaults = struct(...
        'problemId', 5, ...
        'Nx1', 51, ...
        'Nx2', 51, ...
        'Nt1', 50, ...
        'Nt2', 50, ...
        'sampleNs', 200, ...
        'omega1', 0.5, ...
        'omega2', 0.01, ...
        'max_iter', 10, ...
        'pauseTime', 0.1, ...
        'diagonal_reg', 0, ...
        'interpMethod', 'cubic', ...
        'doPlot', 1, ...
        'plotEvery', 1, ...
        'plotInitial', 1, ...
        'showHarmonicPlot', true, ...
        'showHarmonicRes', true ...
    );
    params = meshgen.util.apply_defaults(params, defaults);
end
