function params = defaults_dual(params)
%DEFAULTS_DUAL Set default options for the dual/harmonic-map formulation.
    if nargin < 1
        params = struct();
    end

    defaults = struct(...
        'problemId', 9, ...
        'Nx1', 51, ...
        'Nx2', 51, ...
        'Nt1', 50, ...
        'Nt2', 50, ...
        'sampleNs', 200, ...
        'omega1', 0.5, ...
        'omega2', 0.01, ...
        'max_iter', 10, ...
        'pauseTime', 0.1, ...
        'diagonal_reg', 0, ...
        'interpMethod', 'cubic', ...
        'doPlot', 1, ...
        'plotEvery', 1, ...
        'plotInitial', 1, ...
        'showHarmonicPlot', true, ...
        'showHarmonicRes', true ...
    );
    params = meshgen.util.apply_defaults(params, defaults);

    airfoil_paths = struct(...
        'metric_datapath', '~/Files/data/Mesh_Generation/Airfoil/foil2/metricField.fields', ...
        'airfoil_datapath', '~/Files/data/Mesh_Generation/Airfoil/foil2/airfoil_18M_coarseIJK.grid' ...
    );

    if params.problemId == 5
        problem5_defaults = struct(...
            'grade', 1, ...
            'new_airfoil', 1, ...
            'hyperbolic', 0, ...
            'alpha', 1.005, ...
            'append_trail', 1, ...
            'metric_datapath', airfoil_paths.metric_datapath, ...
            'airfoil_datapath', airfoil_paths.airfoil_datapath ...
        );
        params = meshgen.util.apply_defaults(params, problem5_defaults);
    elseif params.problemId == 9
        problem9_defaults = struct(...
            'grade', 0, 'grade_iterations', 20, ...
            'block_idx', 5, ...
            'metric_datapath', airfoil_paths.metric_datapath, ...
            'airfoil_datapath', airfoil_paths.airfoil_datapath ...
        );
        params = meshgen.util.apply_defaults(params, problem9_defaults);
    end
end
