function cf = defaults_el(cf)
%DEFAULTS_EL Set default options for EL formulation in physical coordinates.
    if nargin < 1
        cf = struct();
    end

    defaults = struct(...
        'problem', 5, ...
        'Nx1', 41, ...
        'Nx2', 41, ...
        'alpha', 1.005, ...
        'sigma1', 1, ...
        'sigma2', 1, ...
        'nonlinear', 7, ...
        'fixed_bc', 0, ...
        'omega', 0.5, ...
        'offdiag', 1, ...
        'max_iter', 500, ...
        'tolerance', 1e-6, ...
        'smooth', 0, ...
        'animation', 1, ...
        'iter_per_frame', 1, ...
        'plot_res', 1, ...
        'pause_time', 0, ...
        'make_gif', 0, ...
        'gif_name', 'failed_example.gif', ...
        'title_name', 'Alternative', ...
        'save_output', 0, ...
        'new_airfoil', 0 ...
    );
    cf = meshgen.util.apply_defaults(cf, defaults);

    if cf.problem == 5
        airfoil_defaults = struct(...
            'grade', 0, ...
            'metric_datapath', '~/Files/data/Mesh_Generation/Airfoil/foil2/metricField.fields', ...
            'airfoil_datapath', '~/Files/data/Mesh_Generation/Airfoil/foil2/airfoil_18M_coarseIJK.grid', ...
            'append_trail', 0 ...
        );
        cf = meshgen.util.apply_defaults(cf, airfoil_defaults);
    end

    if cf.problem == 1 || cf.problem == 2
        cf = meshgen.util.apply_defaults(cf, struct('C', 1));
    end

    if cf.nonlinear == 7
        cf = meshgen.util.apply_defaults(cf, struct('exact', 0));
    end

    if cf.new_airfoil == 1
        cf.metric_datapath = '~/Files/data/Mesh_Generation/Airfoil/foil2/metricField.fields';
        cf.airfoil_datapath = '~/Files/data/Mesh_Generation/Airfoil/foil2/airfoil_18M_coarseIJK.grid';
    end
end
